name: Backend CI

on:
  push:
    branches: [ "main", "feature/*" ]
    paths:
      - 'backend/**'  # Watch changes only in the backend folder
      - '.github/workflows/backend.yml'  # Watch changes to this workflow file itself
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'  # Watch changes only in the backend folder
      - '.github/workflows/backend.yml'  # Watch changes to this workflow file itself
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run install-backend
    - run: npm run build-backend --if-present
    - run: npm run test-backend
